### ISSUE TITLE
ACID compliant

### ISSUE THREAD

**Issue by ljstrnadiii** [NVlabs/tensorcom#2]
Thanks for pointing me to this repo from webdatasets!

I have spent some time looking at zmq and tensorcom. Cool project! I am curious if there is a messaging pattern that will guarantee all elements get processed? 

This works well if we have a training job, but what if we want to make inference over every element and be guaranteed each one is served? Maybe REQ/RESP? I don't think that has been implemented and I think there might be a throughout cost associated with that.

Maybe there is another tool other than zmq you have looked at?

Cheers!

**Comment by tmbdev** [comment]
PUSH/PULL is reliable and still has handshakes, they're simply implemented at the protocol level and set up in a way that they don't slow down streaming apps. Samples/messages are buffered by the server until they are consumed by the client.
